package com.ssd.gem.mbg.mapper;

import com.ssd.gem.mbg.model.GemJournalAccount;
import com.ssd.gem.mbg.model.GemJournalAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GemJournalAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_journal_account
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    int countByExample(GemJournalAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_journal_account
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    int deleteByExample(GemJournalAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_journal_account
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_journal_account
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    int insert(GemJournalAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_journal_account
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    int insertSelective(GemJournalAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_journal_account
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    List<GemJournalAccount> selectByExample(GemJournalAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_journal_account
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    GemJournalAccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_journal_account
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    int updateByExampleSelective(@Param("record") GemJournalAccount record, @Param("example") GemJournalAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_journal_account
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    int updateByExample(@Param("record") GemJournalAccount record, @Param("example") GemJournalAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_journal_account
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    int updateByPrimaryKeySelective(GemJournalAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_journal_account
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    int updateByPrimaryKey(GemJournalAccount record);
}