package com.ssd.gem.mbg.mapper;

import com.ssd.gem.mbg.model.GemOrderProduct;
import com.ssd.gem.mbg.model.GemOrderProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GemOrderProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_order_product
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    int countByExample(GemOrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_order_product
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    int deleteByExample(GemOrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_order_product
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_order_product
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    int insert(GemOrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_order_product
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    int insertSelective(GemOrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_order_product
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    List<GemOrderProduct> selectByExample(GemOrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_order_product
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    GemOrderProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_order_product
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    int updateByExampleSelective(@Param("record") GemOrderProduct record, @Param("example") GemOrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_order_product
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    int updateByExample(@Param("record") GemOrderProduct record, @Param("example") GemOrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_order_product
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    int updateByPrimaryKeySelective(GemOrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_order_product
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    int updateByPrimaryKey(GemOrderProduct record);
}