package com.ssd.gem.mbg.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class GemOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gem_order.id
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gem_order.code
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gem_order.customer_name
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gem_order.customer_tel
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    private String customerTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gem_order.customer_addr
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    private String customerAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gem_order.status
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gem_order.total_amount
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    private BigDecimal totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gem_order.pay_amount
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    private BigDecimal payAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gem_order.order_date
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    private Date orderDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gem_order.remarks
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gem_order
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gem_order.id
     *
     * @return the value of gem_order.id
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gem_order.id
     *
     * @param id the value for gem_order.id
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gem_order.code
     *
     * @return the value of gem_order.code
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gem_order.code
     *
     * @param code the value for gem_order.code
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gem_order.customer_name
     *
     * @return the value of gem_order.customer_name
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gem_order.customer_name
     *
     * @param customerName the value for gem_order.customer_name
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gem_order.customer_tel
     *
     * @return the value of gem_order.customer_tel
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public String getCustomerTel() {
        return customerTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gem_order.customer_tel
     *
     * @param customerTel the value for gem_order.customer_tel
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public void setCustomerTel(String customerTel) {
        this.customerTel = customerTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gem_order.customer_addr
     *
     * @return the value of gem_order.customer_addr
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public String getCustomerAddr() {
        return customerAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gem_order.customer_addr
     *
     * @param customerAddr the value for gem_order.customer_addr
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public void setCustomerAddr(String customerAddr) {
        this.customerAddr = customerAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gem_order.status
     *
     * @return the value of gem_order.status
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gem_order.status
     *
     * @param status the value for gem_order.status
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gem_order.total_amount
     *
     * @return the value of gem_order.total_amount
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gem_order.total_amount
     *
     * @param totalAmount the value for gem_order.total_amount
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gem_order.pay_amount
     *
     * @return the value of gem_order.pay_amount
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gem_order.pay_amount
     *
     * @param payAmount the value for gem_order.pay_amount
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gem_order.order_date
     *
     * @return the value of gem_order.order_date
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gem_order.order_date
     *
     * @param orderDate the value for gem_order.order_date
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gem_order.remarks
     *
     * @return the value of gem_order.remarks
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gem_order.remarks
     *
     * @param remarks the value for gem_order.remarks
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_order
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", customerName=").append(customerName);
        sb.append(", customerTel=").append(customerTel);
        sb.append(", customerAddr=").append(customerAddr);
        sb.append(", status=").append(status);
        sb.append(", totalAmount=").append(totalAmount);
        sb.append(", payAmount=").append(payAmount);
        sb.append(", orderDate=").append(orderDate);
        sb.append(", remarks=").append(remarks);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}