package com.ssd.gem.mbg.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class GemOrderProduct implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gem_order_product.id
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gem_order_product.order_id
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gem_order_product.product_name
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gem_order_product.product_code
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    private String productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gem_order_product.product_param_text
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    private String productParamText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gem_order_product.product_customized_text
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    private String productCustomizedText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gem_order_product.product_quantity
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    private Integer productQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gem_order_product.market_price
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    private BigDecimal marketPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gem_order_product.total_price
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gem_order_product.avg_price
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    private BigDecimal avgPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gem_order_product
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gem_order_product.id
     *
     * @return the value of gem_order_product.id
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gem_order_product.id
     *
     * @param id the value for gem_order_product.id
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gem_order_product.order_id
     *
     * @return the value of gem_order_product.order_id
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gem_order_product.order_id
     *
     * @param orderId the value for gem_order_product.order_id
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gem_order_product.product_name
     *
     * @return the value of gem_order_product.product_name
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gem_order_product.product_name
     *
     * @param productName the value for gem_order_product.product_name
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gem_order_product.product_code
     *
     * @return the value of gem_order_product.product_code
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gem_order_product.product_code
     *
     * @param productCode the value for gem_order_product.product_code
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gem_order_product.product_param_text
     *
     * @return the value of gem_order_product.product_param_text
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public String getProductParamText() {
        return productParamText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gem_order_product.product_param_text
     *
     * @param productParamText the value for gem_order_product.product_param_text
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public void setProductParamText(String productParamText) {
        this.productParamText = productParamText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gem_order_product.product_customized_text
     *
     * @return the value of gem_order_product.product_customized_text
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public String getProductCustomizedText() {
        return productCustomizedText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gem_order_product.product_customized_text
     *
     * @param productCustomizedText the value for gem_order_product.product_customized_text
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public void setProductCustomizedText(String productCustomizedText) {
        this.productCustomizedText = productCustomizedText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gem_order_product.product_quantity
     *
     * @return the value of gem_order_product.product_quantity
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public Integer getProductQuantity() {
        return productQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gem_order_product.product_quantity
     *
     * @param productQuantity the value for gem_order_product.product_quantity
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public void setProductQuantity(Integer productQuantity) {
        this.productQuantity = productQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gem_order_product.market_price
     *
     * @return the value of gem_order_product.market_price
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gem_order_product.market_price
     *
     * @param marketPrice the value for gem_order_product.market_price
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gem_order_product.total_price
     *
     * @return the value of gem_order_product.total_price
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gem_order_product.total_price
     *
     * @param totalPrice the value for gem_order_product.total_price
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gem_order_product.avg_price
     *
     * @return the value of gem_order_product.avg_price
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public BigDecimal getAvgPrice() {
        return avgPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gem_order_product.avg_price
     *
     * @param avgPrice the value for gem_order_product.avg_price
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    public void setAvgPrice(BigDecimal avgPrice) {
        this.avgPrice = avgPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gem_order_product
     *
     * @mbggenerated Wed Mar 18 20:49:33 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderId=").append(orderId);
        sb.append(", productName=").append(productName);
        sb.append(", productCode=").append(productCode);
        sb.append(", productParamText=").append(productParamText);
        sb.append(", productCustomizedText=").append(productCustomizedText);
        sb.append(", productQuantity=").append(productQuantity);
        sb.append(", marketPrice=").append(marketPrice);
        sb.append(", totalPrice=").append(totalPrice);
        sb.append(", avgPrice=").append(avgPrice);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}